# Generated by Django 4.1.7 on 2023-03-07 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={},
        ),
        migrations.AlterModelManagers(
            name='school',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='school',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='school',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='school',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='school',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='school',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='school',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='school',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='school',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='school',
            name='username',
        ),
    ]
