# Generated by Django 4.1.7 on 2023-03-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_alter_school_options_alter_school_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
