# Generated by Django 4.1.7 on 2023-03-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_student_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
